### ISSUE TITLE
Save better solvated PDB files

### ISSUE THREAD

**Issue by Lachele** [GLYCAM-Web/MD_Utils#3]
The solvated PDB files contain no CONECT cards.  They also have TER cards between each residue.  They are currently being written by tleap.  See if some other utility in AMBER will do a better job generating the files.

**Comment by Lachele** [comment]
Update: we have cpptraj write the files out now.  There are ter cards, but  no conect cards.  That is an improvement.

**Comment by gitoliver** [comment]
We only produce these solvated files:
unminimized-t5p.parm7  unminimized-t5p.pdb  unminimized-t5p.rst7.
The pdb file has TER cards between each residue, but no bonding information. If you load this into tleap you'll have to manually add bond commands. For linear oligos you can just remove the TER cards. For branched ones you'll have to either add bond commands for everything, or keep TER cards at branches and add bonds just for those. Ideally we have TER cards between each residue and CONECT cards specifying what to bond.

**Comment by gitoliver** [comment]
Er actually, if you want to simulate these just use unminimized-t5p.parm7 and unminimized-t5p.rst7. If you want to load a solvated system into tleap (unminimized-t5p.pdb), well better to just load the unsolvated min-gas.mol2 file. It has charges and connectivity. Look in unminimized-t3p.leapin or unminimized-t5p.leapin for how we generate the unminimized-t5p.* files from min-gas.mol2. 
Suggest close?

**Comment by Lachele** [comment]
Yes.  I'm good with closing this one.
